export const DEFAULT_SERVICES = [
  "[NGỰC] Nâng ngực túi Motiva ko chip",
  "[NGỰC] Nâng ngực túi Nano chip / Mentor tròn trơn",
  "[NGỰC] Nâng ngực túi Nano chip ergonomix (gel linh hoạt) - USA",
  "[NGỰC] Nâng ngực nội soi túi Mentor Extra (màng sinh học, gel linh hoạt) - USA",
  "[NGỰC] Nâng ngực nội soi túi Mentor Boost (màng sinh học, gel linh hoạt, độ nhô cao) - USA",
  "[NGỰC] Nâng ngực sa trễ cấp độ 1 (kèm đặt túi ngực, sẹo bán nguyệt)",
  "[NGỰC] Nâng ngực sa trễ cấp độ 2 (kèm đặt túi ngực, treo quanh quầng)",
  "[NGỰC] Nâng ngực sa trễ cấp độ 3 (kèm đặt túi ngực, treo sẹo dọc)",
  "[NGỰC] Nâng ngực sa trễ cấp độ 4 (kèm đặt túi ngực, treo sẹo mỏ neo)",
  "[NGỰC] Treo sa trễ cắt tuyến phì đại độ 4 trở lên (ko đặt túi, sẹo mỏ neo)",
  "[NGỰC] Thu ngắn đầu ti / thu nhỏ đầu ti / Kéo núm vú tụt",
  "[MÔNG] Nâng mông nội soi túi Polytech (màng sinh học, gel tròn)",
  "[MÔNG] Nâng mông nội soi túi Motiva (màng sinh học, gel giọt nước)",
  "[MÔNG] Nâng mông nội soi túi Sebbin (màng sinh học, gel linh hoạt)",
  "[BỤNG] Phẫu thuật hút mỡ toàn bụng đơn thuần 6 vùng",
  "[BỤNG] Phẫu thuật hút mỡ + tạo hình thành bụng mini",
  "[BỤNG] Phẫu thuật hút mỡ + tạo hình thành bụng toàn bộ chuyển rốn",
  "[HÚT MỠ] Hút mỡ toàn bụng 6 vùng",
  "[HÚT MỠ] Hút mỡ lưng 6 vùng",
  "[HÚT MỠ] Hút mỡ đùi 6 vùng",
  "[HÚT MỠ] Hút mỡ bắp tay",
  "[HÚT MỠ] Hút mỡ bắp chân",
  "[CẤY MỠ] Cấy mỡ ngực (bao gồm hút)",
  "[CẤY MỠ] Cấy mỡ mông (bao gồm hút)",
  "[CẤY MỠ] Cấy mỡ toàn mặt (thái dương, trán, má, rãnh cười, cằm, tai)",
  "[CẤY MỠ] Cấy mỡ vùng bikini",
  "[CẤY MỠ] Cấy mỡ thái dương / má hóp",
  "[MŨI] Nâng mũi Thailand chất liệu Mỹ (Softxil, Safesil..)",
  "[MŨI] Nâng mũi bán cấu trúc bọc đầu mũi, dựng vách ngăn chất liệu Mỹ",
  "[MŨI] Nâng mũi cấu trúc (bọc đầu mũi + tái tạo vách ngăn, thu xương bè, mài gồ)",
  "[MŨI] Nâng mũi cấu trúc chất liệu sụn sinh học (Nanoform, Surgiform)",
  "[MŨI] Nâng mũi cấu trúc sụn sườn tự thân, bọc cân cơ",
  "[MŨI] Thu nhỏ cánh mũi",
  "[MŨI] Thu nhỏ đầu mũi",
  "[MŨI] Thu nhỏ nền mũi",
  "[CẰM] Độn cằm V-line Thailand",
  "[CẰM] Độn cằm V-line sụn sinh học",
  "[CẰM] Trượt cằm Diamond line",
  "[CẰM] Gọt hàm đường trong miệng",
  "[CẰM] Phẫu thuật hạ hàm hô",
  "[CẰM] Phẫu thuật hạ gò má nội soi",
  "[MẮT] Cắt mí mini",
  "[MẮT] Cắt mí Thailand / Ấn Độ",
  "[MẮT] Căng da lấy mỡ mí dưới",
  "[MẮT] Nâng cung mày",
  "[MẮT] Tái tạo cơ nâng mi sụp bẩm sinh",
  "[MẮT] Chỉnh sửa mí lỗi hỏng",
  "[MÔI - MÁ] Tạo má lúm 1 bên / 2 bên",
  "[MÔI - MÁ] Tạo hình môi trái tim",
  "[MÔI - MÁ] Tạo hình môi chẻ",
  "[MÔI - MÁ] Tạo hình khoé cười",
  "[MÔI - MÁ] Thu mỏng môi",
  "[MẶT] Độn thái dương",
  "[MẶT] Độn trán",
  "[MẶT] Căng da trán",
  "[MẶT] Căng da mặt mini",
  "[MẶT] Căng da toàn mặt (căng da trán + căng da mini)",
  "[TẦNG SINH MÔN] Thẩm mỹ môi lớn / môi bé",
  "[TẦNG SINH MÔN] Thu nhỏ âm đạo / Tạo hình màng trinh",
  "[TẦNG SINH MÔN] Tạo hình nâng cơ tầng sinh môn"
];
